baseurl = "https://sierxue.netlify.com/"
relativeurls = true
languageCode = "en-us"
title = "甘湘华 | Xianghua Gan"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = ":slug/"

[[menu.main]]
    name = "简历"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "博客"
    url = "/post/"
[[menu.main]]
    name = "机器学习"
    url = "/series/ml/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [taxonomies]
      tag = "tags"
      category = "categories"
      series = "series"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

