baseurl = "https://sierxue.netlify.com/"
relativeurls = true
languageCode = "cn-zh"
title = "甘湘华 | Xianghua Gan"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = ":slug/"

[[menu.main]]
    name = "博客"
    url = "/post/"
    weight = 1
[[menu.main]]
    name = "机器学习"
    url = "/series/ml/"
    weight = 5
[[menu.main]]
    name = "简历"
    url = "/about/"
    weight = 9

[params]
    description = "甘湘华的个人网站; Personal website of Xianghua Gan"
    fullURL = "/"
    customCSS = ["css/custom.css"]
    customJS = ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]
    githubContentURL = ""

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
    [social]
      weibo = ""
      weibo_url = ""
      github = "sierxue"

    [taxonomies]
      tag = "tags"
      category = "categories"
      series = "series"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "甘湘华 Xianghua Gan"
    
    [author]
      post = "甘湘华"

    [lang]
      [edit]
        post = "编辑本页"

    [blackfriday]
      extensionsmask = ["noIntraEmphasis"]