---
date: 2017-05-24 7:00:00
title: "1.2 机器学习的应用范围"
author: "甘湘华"
show_toc: true
series: [ML]
categories: [MLF01]
tags: []
---

让我们先看两个动物学习的例子，这些例子启发了机器学习中最基本的研究课题。

1. 老鼠试食；
2. 鸽的迷信。
<!-- more -->

## 例1：老鼠试食

老鼠试食 - 通过学习来避免有毒诱饵：
当老鼠遇到具有新外观或气味的食物，它们会先吃非常少的量，随后的摄食将取决于食物的味道和产生的生理作用。如果摄入的食物产生不良影响，老鼠就把这种食物和不良影响联系起来，也就不吃这种食物了。显然，这里有一个学习的机制--动物通过以往进食的经验获取侦测食物是否安全的知识。如果以过去的经验判断某类食物为有毒的话，当今后遇到类似的食物是，动物就会认为它是有毒的。

受上面例子的启发，我们演示一个机器学习中的一个超越人类能力的任务：另一个广泛的家庭任务

从机器学习技术效益的分析相关的SIS系统非常庞大和复杂的数据集：天文数据，将医疗档案到医学知识，天气预报，分析基因组数据分析、搜索引擎、电子商务。随着越来越多的可用数字记录的数据，显而易见的是，有大量有意义的信息埋藏在数据档案中，对人类来说是太大太复杂了。学习发现有意义的模式在大型和复杂的数据集是一种很有前途的领域，结合国家项目，学习与几乎无限的存储能力和不断增加的电脑处理速度，开辟了新的视野。典型任务：垃圾邮件过滤。一个朴素的想法是记住用户们标注的垃圾邮件 --- 建立一个发送垃圾邮件的邮箱地址的数据库。当一封邮件寄来时，我们检查这封邮件的发件地址是否在垃圾邮箱数据库中，如果在，我们就过滤掉它。虽然这种方法在某些时候也是有用的，但是它缺乏学习系统中一个重要的要素 --- 判别一个未知邮件地址是否垃圾邮箱的能力。

一个成功的学习者应该能从一些个例中得到更一般化的结论，这个方法我们通常称为归纳推理 (Inductive reasoning 或 inductive inference)。
在老鼠的例子里，如果老鼠有过某种食物的经验，他们就会这种经验用到类似的但不曾见过的食物上。
类似地，在垃圾邮件过滤的问题中，学习者可以扫描先前收到的垃圾邮件，并且提取出一些能表明是垃圾邮件的词汇。
这样，当一封新邮件到达时，机器就可以检查是否一些可疑的词汇出现在里面，并且做出是否为垃圾邮件的判定。
这个系统就有可能以大概率准确标出新的垃圾邮件。

然而，归纳推理可能导致一些错误的决定。我们用一个动物学习的例子来说明这一点。

## 例2：鸽的迷信

斯金纳是一位久负盛名的心理学家，堪称行为主义之父，他是著名的“斯金纳箱”的发明者。
他曾经做过一次实验，把8只鸽子放到一个笼子里。
^[<http://www.psychspace.com/psych/viewnews-371>]
食物分发器被设定为每隔15秒落下食丸，不管动物当时在做什么。
可以看到这便产生了非关联性强化。换句话说，不管动物做了什么，每隔15秒它将得到一份奖励。
连续几天对这些鸽子喂少于他们正常进食量的食物，以便在测试时，它们处于饥饿状态。
由此增强寻找食物的动机（这增加了强化的效果）。
让每只鸽子每天在实验箱里待几分钟，对其行为不作任何限制。
在这期间，每个15秒强化自动出现。几天后，两个独立的观测者记录了鸽子在箱中的行为。

斯金纳在报告中写道：“8只鸽子中的6只产生了非常明显的反应，两名观察者得到了完全一致的记录。
一只鸽子形成了在箱子中逆时针转圈的条件反射，在两次强化之间转2到3圈；
另一只反复将头撞向箱子上方的一个角落；
第三只只显现出一种上举反应，似乎把头放在一根看不见的杆下面并反复抬起它。
还有两只鸽子的头和身体呈现出一种摇摆似的动作，它们头部前伸，并且从右向左大幅度摇摆，
接着再慢慢的转过来，它们的身子也顺势移动，动作幅度过大时还会向前走几步。
还有一只鸽子形成了不完整的啄击或轻触的条件反应，动作直冲地面但并不接触。”
上述的行为都是在建立条件反射前未曾观测到的。实际上新的行为和鸽子得到食物毫无联系。
然而，它们表现的就好像行为会产生食物似的；也就是说，它们变得迷信了。
接下来，斯金纳想知道如果两次强化之间的间隔被拉长了，又会发生什么。
他用了一只摇头的鸽子，然后把两次投放食丸的时间间隔慢慢增加到1分钟。
这时，鸽子表现的更加精力充沛，直到最后在两次强化间的 1 分钟内，这只鸽子像在表演一种舞蹈（好像一种“鸽子食物舞”）。
最后是消除鸽子的这种新行为。这意味着在测试箱中的强化不再出现。
这时，迷信行为逐渐消退，直到完全消失。
然而，值得注意的是，这只“跳舞”的鸽子在完全消退前的这种反应次数超过了1 万次。


有什么能把迷信和有用的学习区分开来？这个问题对于自动学习着来说是一个至关重要的问题。
虽然人能够根据一些常识过滤掉随机的无意义结论，但机器不能。一旦我们把任务交给机器去做，
我们必须提供提供明确的原理和准则，使机器免于得到无意义或者无用的结果。
探寻这些原理是机器学习的一个核心目的。

<!-- 接下来，我们更深入地研究老鼠试食的例子，探寻为什么老鼠的学习会比鸽子的学习更成功。 -->
